# Generated by Django 5.2 on 2025-04-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hodnoceni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='datum_upraveni',
        ),
        migrations.RemoveField(
            model_name='place',
            name='datum_vytvoreni',
        ),
    ]
