# Generated by Django 4.2.20 on 2025-04-25 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hodnoceni', '0002_remove_place_datum_upraveni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='datum_upraveni',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='datum_vytvoreni',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
