# Generated by Django 4.2.20 on 2025-04-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodnoceni', '0003_remove_place_place_id_alter_review_datum_upraveni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
