# Generated by Django 4.2.20 on 2025-04-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodnoceni', '0005_remove_review_datum_upraveni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
