# Generated by Django 4.2.20 on 2025-04-29 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hodnoceni', '0008_remove_place_place_id_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='datum_upraveni',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='datum_vytvoreni',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
